### ISSUE TITLE
Clean up the warnings or 2.11

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1139] opened 2014-12-18 23:42 UTC
We have a bunch of no-op transient annotations it looks like.

For instance:

```
[warn] /Users/oscar/workspace/scalding/scalding-core/src/main/scala/com/twitter/scalding/Operations.scala:297: no valid targets for annotation on value inputRfn - it is discarded unused. You may specify targets with meta-annotations, e.g. @(transient @param)
[warn]     @transient inputRfn: (X, X) => X,
[warn]      ^
[warn] /Users/oscar/workspace/scalding/scalding-core/src/main/scala/com/twitter/scalding/Operations.scala:298: no valid targets for annotation on value inputMrfn - it is discarded unused. You may specify targets with meta-annotations, e.g. @(transient @param)
[warn]     @transient inputMrfn: X => U,
[warn]      ^
[warn] /Users/oscar/workspace/scalding/scalding-core/src/main/scala/com/twitter/scalding/Operations.scala:396: no valid targets for annotation on value inputMrfn - it is discarded unused. You may specify targets with meta-annotations, e.g. @(transient @param)
[warn]     @transient inputMrfn: T => X,
[warn]      ^
[warn] /Users/oscar/workspace/scalding/scalding-core/src/main/scala/com/twitter/scalding/Operations.scala:397: no valid targets for annotation on value inputRfn - it is discarded unused. You may specify targets with meta-annotations, e.g. @(transient @param)
[warn]     @transient inputRfn: (X, X) => X,
[warn]      ^
[warn] /Users/oscar/workspace/scalding/scalding-core/src/main/scala/com/twitter/scalding/Operations.scala:431: no valid targets for annotation on value init - it is discarded unused. You may specify targets with meta-annotations, e.g. @(transient @param)
[warn]     @transient init: I,
[warn]      ^
[warn] /Users/oscar/workspace/scalding/scalding-core/src/main/scala/com/twitter/scalding/Operations.scala:432: no valid targets for annotation on value inputIterfn - it is discarded unused. You may specify targets with meta-annotations, e.g. @(transient @param)
[warn]     @transient inputIterfn: (I, Iterator[T]) => TraversableOnce[X],
[warn]      ^
[warn] /Users/oscar/workspace/scalding/scalding-core/src/main/scala/com/twitter/scalding/Operations.scala:450: no valid targets for annotation on value init - it is discarded unused. You may specify targets with meta-annotations, e.g. @(transient @param)
[warn]     @transient init: I,
[warn]      ^
[warn] /Users/oscar/workspace/scalding/scalding-core/src/main/scala/com/twitter/scalding/Operations.scala:452: no valid targets for annotation on value inputIterfn - it is discarded unused. You may specify targets with meta-annotations, e.g. @(transient @param)
[warn]     @transient inputIterfn: (I, C, Iterator[T]) => TraversableOnce[X],
[warn]      ^
[warn] /Users/oscar/workspace/scalding/scalding-core/src/main/scala/com/twitter/scalding/Operations.scala:486: no valid targets for annotation on value reduceFn - it is discarded unused. You may specify targets with meta-annotations, e.g. @(transient @param)
[warn]     @transient reduceFn: (K, Iterator[V]) => Iterator[U],
```

**Comment by ianoc** [comment] 2015-01-12 06:24
These warnings are possibly in error related to -- https://issues.scala-lang.org/browse/SI-8813

**Comment by johnynek** [comment] 2015-04-27 19:09
Other warnings, if they exist, should be fixed.

**Comment by oeddyo** [comment] 2015-05-01 18:59
Taking a look...


To reproduce the warnings:
./sbt ++2.11.5 test

**Comment by oeddyo** [comment] 2015-05-01 19:38
Strange enough Travis is not happy about the change (or maybe due to other cause?):

**Comment by rubanm** [comment] 2015-05-01 22:58
There is a fix for this from @MansurAshraf https://github.com/twitter/scalding/pull/1270

Pulling that in once it's merged should fix it for you.

**Comment by oeddyo** [comment] 2015-05-02 06:51
Do we want to get rid of these warnings too?: They appear both in 2.10 and 2.11

[warn] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[warn] /Users/exie/learn/ScaldingGithub/scalding/maple/src/main/java/com/twitter/maple/hbase/HBaseTap.java:36: warning: NotImplementedException is internal proprietary API and may be removed in a future release
[warn] import sun.reflect.generics.reflectiveObjects.NotImplementedException;
[warn]                                              ^
[warn] Note: Some input files use or override a deprecated API.
[warn] Note: Recompile with -Xlint:deprecation for details.
[warn] Note: Some input files use unchecked or unsafe operations.
[warn] Note: Recompile with -Xlint:unchecked for details.
[warn] 2 warnings
[info] Compiling 8 Scala sources to /Users/exie/learn/ScaldingGithub/scalding/scalding-date/target/scala-2.10/classes...
[warn] /Users/exie/learn/ScaldingGithub/scalding/scalding-date/src/main/scala/com/twitter/scalding/RichDate.scala:53: match may not be exhaustive.
[warn] It would fail on the following input: Some((x: String forSome x not in (DATEHOUR_WITH_DASH, DATETIME_HMSM_WITH_DASH, DATETIME_HMS_WITH_DASH, DATETIME_WITH_DASH, DATE_WITH_DASH)))
[warn]     (DateOps.getFormat(s) match {
[warn]                       ^
[warn] one warning found
[info] Compiling 2 Scala sources to /Users/exie/learn/ScaldingGithub/scalding/scalding-args/target/scala-2.10/classes...
[info] Formatting 3 Scala sources {file:/Users/exie/learn/ScaldingGithub/scalding/}scalding-avro(compile) ...
[info] Formatting 2 Scala sources {file:/Users/exie/learn/ScaldingGithub/scalding/}scalding-json(compile) ...
[info] Formatting 5 Scala sources {file:/Users/exie/learn/ScaldingGithub/scalding/}scalding-jdbc(compile) ...
[info] Formatting 4 Scala sources {file:/Users/exie/learn/ScaldingGithub/scalding/}scalding-parquet(compile) ...
[info] Formatting 4 Scala sources {file:/Users/exie/learn/ScaldingGithub/scalding/}scalding-hadoop-test(compile) ...
[info] Formatting 1 Scala source {file:/Users/exie/learn/ScaldingGithub/scalding/}scalding-hraven(compile) ...
[info] Formatting 11 Scala sources {file:/Users/exie/learn/ScaldingGithub/scalding/}scalding-commons(compile) ...
[info] Formatting 4 Scala sources {file:/Users/exie/learn/ScaldingGithub/scalding/}scalding-repl(compile) ...
[info] Formatting 1 Scala source {file:/Users/exie/learn/ScaldingGithub/scalding/}scalding-parquet-scrooge(compile) ...
[info] Formatting 6 Scala sources {file:/Users/exie/learn/ScaldingGithub/scalding/}scalding-macros(compile) ...
[info] Compiling 5 Scala sources to /Users/exie/learn/ScaldingGithub/scalding/scalding-date/target/scala-2.10/test-classes...
[info] Compiling 2 Scala sources to /Users/exie/learn/ScaldingGithub/scalding/scalding-args/target/scala-2.10/test-classes...
[info] Compiling 113 Scala sources and 1 Java source to /Users/exie/learn/ScaldingGithub/scalding/scalding-core/target/scala-2.10/classes...
[warn] /Users/exie/learn/ScaldingGithub/scalding/scalding-core/src/main/scala/com/twitter/scalding/CumulativeSum.scala:42: abstract type pattern U is unchecked since it is eliminated by erasure
[warn]         .sortBy { case (u: U, _) => u }
[warn]                            ^
[warn] /Users/exie/learn/ScaldingGithub/scalding/scalding-core/src/main/scala/com/twitter/scalding/CumulativeSum.scala:44: abstract type pattern U is unchecked since it is eliminated by erasure
[warn]           case (acc, (u: U, v: V)) =>
[warn]                          ^
[warn] /Users/exie/learn/ScaldingGithub/scalding/scalding-core/src/main/scala/com/twitter/scalding/CumulativeSum.scala:44: abstract type pattern V is unchecked since it is eliminated by erasure
[warn]           case (acc, (u: U, v: V)) =>
[warn]                                ^
[warn] /Users/exie/learn/ScaldingGithub/scalding/scalding-core/src/main/scala/com/twitter/scalding/CumulativeSum.scala:66: abstract type pattern U is unchecked since it is eliminated by erasure
[warn]         .map { case (k, (u: U, v: V)) => (k, partition(u)) -> v }
[warn]                             ^
[warn] /Users/exie/learn/ScaldingGithub/scalding/scalding-core/src/main/scala/com/twitter/scalding/CumulativeSum.scala:66: abstract type pattern V is unchecked since it is eliminated by erasure
[warn]         .map { case (k, (u: U, v: V)) => (k, partition(u)) -> v }
[warn]                                   ^
[warn] /Users/exie/learn/ScaldingGithub/scalding/scalding-core/src/main/scala/com/twitter/scalding/CumulativeSum.scala:90: abstract type pattern U is unchecked since it is eliminated by erasure
[warn]           case (k, (u: U, v: V)) =>
[warn]                        ^
[warn] /Users/exie/learn/ScaldingGithub/scalding/scalding-core/src/main/scala/com/twitter/scalding/CumulativeSum.scala:90: abstract type pattern V is unchecked since it is eliminated by erasure
[warn]           case (k, (u: U, v: V)) =>
[warn]                              ^

**Closed** 2015-05-05 17:21 UTC
Labels: beginner
