### ISSUE TITLE
Problems with tuples and map-side reduce.

### ISSUE THREAD

**Issue by wbertelsen** [twitter/scalding#1154] opened 2015-01-09 01:23 UTC
At Foursquare all our hadoop jobs consume and output thrift (https://thrift.apache.org/) records full of optional fields. 

I've run into an issue where, under certain conditions when putting my thrift objects in a tuple, by the time the come back out of the Scalding/Cascading tupleing process all their fields are missing. Specifically this seems tied to instances where Scalding will opt to do a map-side reduce - In the example below everything is fine once I add a .forceToReducers call.

ie, if I do:
```scala 
 val thriftData: TypedPipe[(ThriftKey, ThriftValue)] = ...
  val processedThriftData = {
    thriftData.groupBy(_._1.optionalSubKeyOrDefault).head.toTypedPipe.flatMap {
      case (subKey, (thriftKey, thriftValue)) => process(thriftKey, thriftValue)
    }
  }
```
By the time my data gets to `process` the fields of both `thriftKey` and `thriftValue` will be missing.

on the other hand if i do:
```scala 
 val thriftData: TypedPipe[(ThriftKey, ThriftValue)] = ...
  val processedThriftData = {
    thriftData.groupBy(_._1.optionalSubKeyOrDefault).forceToReducers.head.toTypedPipe.flatMap {
      case (subKey, (thriftKey, thriftValue)) => process(thriftKey, thriftValue)
    }
  }
```
everything is dandy in `process`.

I think the missing fields is a symptom of something throwing away the `thriftValue` bytes but still successfully deserializing it back into a valid `ThriftValue`.

My suspicion is that without the `forceToReducers` when `.head` gets called it ends up doing a `sumByLocalKeys`, which uses a `singleConverter` which screws up my data.

I think there is a bug here, but I could also be doing something dumb. Any ideas?

**Comment by ianoc** [comment] 2015-01-09 01:39
Do you have the chill thrift serializer wired in ? Kryo fields serializer
can have problems on occasion. Also do you know if any values have this bad
property ?

**Comment by wbertelsen** [comment] 2015-01-09 01:51
We don't, we just let Scalding serialize how it cares to (assuming with Kryo based on your comment).  
I can try getting us onto chill if thats the fix.

What do mean by your last question?

**Comment by johnynek** [comment] 2015-01-09 05:59
At twitter, the pattern is to set up a base job (we call TwitterJob), which overrides the config to add serializations to the kryo serializer:

https://github.com/twitter/scalding/blob/develop/scalding-core/src/main/scala/com/twitter/scalding/Config.scala#L124

We add protobuf, scrooge-scala, and tbase thrift (all in chill).

**Comment by johnynek** [comment] 2015-01-09 06:02
To be more verbose, just make a

```scala
class FourSquareInstantiator extends KryoHadoop {
  def newKryo = {
    val k = super.newKryo
    // see: https://github.com/twitter/chill/blob/develop/chill-thrift/src/main/java/com/twitter/chill/thrift/TBaseSerializer.java#L36
    k.addDefaultSerializer(classOf[TBase[_, _]], classOf[TBaseSerializer])
    k
  }
}
```

**Comment by tdyas** [comment] 2015-01-09 18:14
We do use the pattern suggested. `ScaldingMainJob` in our code base overrides `ioSerializations` to add `ThriftSerialization` and `DateTimeSerialization`. Is `ioSerializations` not a recommended way of configuring this?

**Comment by johnynek** [comment] 2015-01-09 18:19
You can use Hadoop serializations for sure, but the problem comes with
nested scala tuples of your types. In that case Hadoop serialization is not
picked up and you would need a Kryo serializer.

If you are not having a problem, don't worry about it. But the default kryo
fails on Thrift (in some cases) so we add specific thrift (and protobuf and
Scrooge) support via chill.

On Friday, January 9, 2015, Tom Dyas <notifications@github.com> wrote:

> We do use the pattern suggested. ScaldingMainJob in our code base
> overrides ioSerializations to add ThriftSerialization and
> DateTimeSerialization. Is ioSerializations not a recommended way of
> configuring this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1154#issuecomment-69374339>.
>


-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by tdyas** [comment] 2015-02-07 03:25
I believe I found a possible cause of the issue. While a custom `KryoInstantiator` probably needs to be installed, I found a potential bug in `com.twitter.scalding.MapsideReduce` where it hard-codes use of `com.twitter.scalding.serialization.Externalizer` which itself hardcodes use of `com.twitter.scalding.serialization.KryoHadoop` and not any custom subclass of `KryoInstantiaor` installed in the configuration.

As suggested, I installed a custom subclass of `KryoHadoop` into the Scalding `Config` configured with `TBaseSerializer`. I verified that it was installed by actually installing a proxy `Serializer` that logged all calls. It was invoked, but it in the case where `MapsideReduce` was used, the proxy was given empty Thrift instances to serialize. This means that the serializer is not actually the issue. Indeed, when `.forceToReducers' is in play, the serializer is invoked and actually serializes non-empty Thrift instances.

I examined `com.twitter.scalding.MapsideReduce` and noted that it directly creates a `com.twitter.scalding.serialization.Externalizer` which itself hardcodes `com.twitter.scalding.serialization.KryoHadoop`. Therefore, my custom subclass of KryoHadoop had no chance of being used in the case where `MapsideReduce` is in the operation graph. The custom subclass is used when `.forceToReducers` is in play.

I tried threading through a `com.twitter.scalding.Config` so I could call `.getKryo` but it will require a non-trivial amount of effort to thread it through.

Can you suggest a way to make `Externalizer` respect the `KryoInstantiator` set in the Scalding configuration?

**Comment by tdyas** [comment] 2015-02-09 20:16
Mutability sucks. The issue was not a serialization issue at all. The Thrift instances used by the input format are reused and cleared on each iteration through the underlying input split. Adding `.mapValues(t => (t._1.copy(), t._2.copy()))` to pipe in the example in this issue fixed the issue.

Cascading uses the old-style Hadoop input format (`org.apache.hadoop.mapred.InputFormat`). The main requirement of the old-style API is that the keys and values produced by the input format must be reusable. (The `.next` method in the input format receives instances of the key and value as parameters and is expected to write data into those instances. There is no option in the old-style API to return the key and value instead.)

In our case, those instances are cleared by our input format before deserializing the next value. Since `com.twitter.scalding.MapsideReduce` caches key/values in an Algebird `SummingCache`, the cached instances were being cleared while in the cache. So there was still a `Tuple2` of Thrift instances, just cleared out ones. Boom.

Going to close this issue. The ultimate fix would be for Cascading to use the new-style (i.e., years old) Hadoop input format which supports returning keys and values (and does not require reusing instances).

**Comment by johnynek** [comment] 2015-02-09 20:29
Glad you got to the bottom of this.

Have you considered using https://github.com/twitter/scrooge ? Yeah, mutability does suck (strictly speaking, scrooge is mutable under the hood, but we never mutate them and there is a plan to make them use immutable APIs on everything public).

**Comment by tdyas** [comment] 2015-02-09 22:28
I don't believe Scrooge would help. The issue is that our custom `Scheme` reuses the key and value instances just like the input format it uses which implements the old-style MR InputFormat API. Given I control the `Scheme` at issue, I will make it stop reusing Thrift instances. (Indeed, if we were to use Scrooge, the same issue would occur because of the way the `Scheme` and `InputFormat` are written.)

**Comment by johnynek** [comment] 2015-02-09 22:33
Well, the Scrooge Immutable instances cannot be reused. So it would have
forced the issue. Also as a side note, they are much safer to use with
optional thrift fields.

On Monday, February 9, 2015, Tom Dyas <notifications@github.com> wrote:

> I don't believe Scrooge would help. The issue is that our custom Scheme
> reuses the key and value instances just like the input format it uses which
> implements the old-style MR InputFormat API. Given I control the Scheme
> at issue, I will make it stop reusing Thrift instances. (Indeed, if we were
> to use Scrooge, the same issue would occur because of the way the Scheme
> and InputFormat are written.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1154#issuecomment-73604439>.
>


-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by julienledem** [comment] 2015-02-09 22:35
Hi Tom,
If the old mapred api expects you to reuse the instance of the key and the
value, you don't have to reuse the thrift instance itself.
What you can do is use a wrapper around it that serves as the value type.
and always make a new thrift instance in your Schema, that you set in that
wrapper.
Julien

**Closed** 2016-02-02 22:05 UTC
