### ISSUE TITLE
Slow TypedPipe.sketch performance with typed mapside reduce operation

### ISSUE THREAD

**Issue by spapin** [twitter/scalding#1565] opened 2016-06-02 16:27 UTC
The change #1508 introduces mapside reduce operation that generally have a performance gain. However in the case of TypedPipe.sketch there is actually a slowdown.

Sketched creates a CounMinSketch monoid and sums it. The creation of the CounMinSketch is expensive. The mapside reduce operations creates comparatively more instance of CountMinSketch and the overall performance is degraded for large datasets.

**Comment by johnynek** [comment] 2016-06-06 18:35
How much slower is it? Can you share some numbers?

It is hard to make tradeoffs when we have data showing wins in one area. This is a bummer.

**Comment by avibryant** [comment] 2016-06-06 19:18
It seems plausible that we don't even want to use the standard mapside reduce for `TypedPipe.sketch`. We know there is going to be exactly one key, so most of the code doesn't really apply. We also don't really need all of the generality and immutability of the standard CMS implementation; we might well be better with a small, optimized, mutable CMS that we use directly from the sketch code. I bet even independent of this latest regression we could improve performance considerably.

**Comment by spapin** [comment] 2016-06-06 21:17
We run a map operation on skewed data over 5,000~20,000 cores and 1B~50B rows. 
The step used to run in about 1 hour. Now we're not even done with half the mappers in 20+ hours.

Trying to add .forceToReducers to the groupAll operation in Sketched.scala but while it fixed the mapper side, the reducer then never completed.

**Comment by avibryant** [comment] 2016-06-06 21:27
Ouch.

What information have you collected that points to #1508 specifically?

**Comment by johnynek** [comment] 2016-06-06 21:27
@spapin did the bisect find the exact patch on that regression?

**Comment by johnynek** [comment] 2016-06-06 21:28
@avibryant +1 to using a more optimized sketching approach. We can use `sumOption` on the CMS with some wrapper tricks (that are almost certainly worth it here).

**Comment by spapin** [comment] 2016-06-06 22:04
Yes a bisect confirms the origin is #1508 

We noticed that there is higher GC and ~30x more bytes written on the failling mappers. But that is probably related to the different structure being outputted on the mappers.

**Comment by ningyue** [comment] 2016-06-16 19:09
+1 We also see performance regression on sketch join. Any work around we could apply for now before sketch is fixed? Thanks!

**Comment by rubanm** [comment] 2016-06-24 21:03
@johnynek @ianoc Any objections to reverting https://github.com/twitter/scalding/pull/1508 on develop? We could bring it back once the ongoing CMS and SketchJoin improvements have been merged. It'll be nice if we can avoid spawning a one-off branch for cutting a RC and getting Twitter jobs using sketch going again.

**Comment by ianoc** [comment] 2016-06-24 21:44
I'd be slow to revert on develop, just since develop is sort of the develop branch, its just where we should be looking for a test that sees a regression/fails or the fix. I think it makes more sense to do a revert on a release branch possibly.  (Since in theory we wouldn't be releasing off develop all the time... it could bring other changes to people). But i don't mind too much.

**Comment by ianoc** [comment] 2016-06-24 21:48
The mappers in either case here should be producing the same amount of data afaik, this doesn't change ondisk representation. Does anyone have Xprofs or other stats for this?

**Comment by rubanm** [comment] 2016-06-24 22:59
We discussed in the gitter room, but posting the xprof here for the record

```
 Compiled + native   Method                        
 43.6% 3000764  + 16893  scala.collection.Iterator$class.foreach
 36.0% 2462997  + 31132  scala.collection.IterableLike$class.zip
 11.4% 788926  +     0   scala.collection.generic.GenTraversableFactory.tabulate
  7.2% 494925  +     0   com.twitter.algebird.IndexedSeqSemigroup.plus
  0.5% 31751  +    52    com.twitter.algebird.CMSInstance$CountsTable.$plus
  0.3%     0  + 17969    scala.collection.immutable.VectorPointer$class.gotoNextBlockStartWritable
  0.1%  4982  +     8    com.twitter.ml.vw.adapter.VWStringAdapter.adaptFromDataRecord
  0.1%  3945  +     3    java.util.TreeMap.put
  0.1%  3490  +    28    com.twitter.ml.vw.adapter.VWStringAdapter.buildFeatureKeyValueString
  0.1%  3471  +     0    scala.collection.Iterator$$anon$11.next
  0.0%  2572  +    23    com.twitter.algebird.Semigroup$.plus
  0.0%  2460  +    26    java.lang.String.split
  0.0%  2402  +     0    org.apache.hadoop.io.compress.DecompressorStream.read
  0.0%  2172  +    29    sun.nio.cs.UTF_16LE.newEncoder
  0.0%  2142  +     0    com.twitter.ml.api.FeatureIterators$ConcatFeatureIterator.moveNext
  0.0%  1963  +     0    java.util.regex.Pattern$BmpCharProperty.match
  0.0%  1891  +     1    scala.collection.TraversableLike$$anonfun$scanLeft$1.apply
  0.0%  1597  +     0    sun.nio.cs.UnicodeEncoder.encodeLoop
  0.0%  1439  +     2    com.twitter.ml.api.RichDataRecord$SparseContinuousSingleFeatureIterator.getFeature
  0.0%  1369  +    16    com.twitter.ml.api.FeatureUtil.getSparseFeatureId
  0.0%  1320  +     0    java.lang.Long.getChars
  0.0%  1256  +     0    scala.collection.Iterator$$anon$11.hasNext
  0.0%  1236  +     1    scala.collection.Iterator$$anon$12.nextCur
  0.0%  1233  +     0    org.apache.hadoop.io.compress.DecompressorStream.read
  0.0%  1206  +     0    scala.collection.immutable.VectorBuilder.result
100.0% 6851072  + 66729  Total compiled (including elided)
```

https://github.com/twitter/algebird/issues/533 and a corresponding Scalding change will address this.

**Closed as completed** 2016-07-28 20:30 UTC

**Comment by johnynek** [comment] 2016-07-29 04:06
@spapin I assume all is well now?
